# Generated by Django 4.0.6 on 2022-08-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_field1_user_field2_user_field3_user_field4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
