# Generated by Django 4.0.6 on 2022-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Profile Image'),
        ),
    ]
