# Generated by Django 4.0.6 on 2022-08-20 13:06

import api.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_follow_deleted_like_deleted_post_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='last_update',
            field=models.DateTimeField(default=api.functions.get_today),
        ),
        migrations.AddField(
            model_name='like',
            name='last_update',
            field=models.DateTimeField(default=api.functions.get_today),
        ),
    ]
