# Generated by Django 4.0.6 on 2022-08-22 01:39

import api.functions.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_follow_last_update_like_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_contents',
            field=models.ImageField(blank=True, upload_to='posts', validators=[api.functions.functions.validate_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='profs', validators=[api.functions.functions.validate_image], verbose_name='Profile Image'),
        ),
    ]
