# Generated by Django 4.0.6 on 2022-08-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_post_image_contents_alter_user_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_contents',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='profs', verbose_name='Profile Image'),
        ),
    ]
