# Generated by Django 4.0.6 on 2022-08-24 16:26

import api.functions.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_post_image_contents_alter_user_prof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pid',
            field=models.CharField(default=api.functions.functions.generate_random_string, max_length=10),
        ),
    ]
