# Generated by Django 4.0.6 on 2022-08-24 22:42

import api.functions.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='api.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.CharField(default=api.functions.functions.generate_random_string, max_length=10, unique=True),
        ),
    ]
