# Generated by Django 4.0.6 on 2022-11-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_annoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='annoy',
            field=models.BooleanField(default=False, verbose_name='Annoy User'),
        ),
    ]
