# Generated by Django 4.0.6 on 2022-11-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_annoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ad',
            field=models.BooleanField(default=False, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='user',
            name='advertiser',
            field=models.BooleanField(default=False, verbose_name='Advertiser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last Name'),
        ),
    ]
