# Generated by Django 4.0.6 on 2022-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_post_ad_user_advertiser_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ad',
            field=models.BooleanField(default=False, verbose_name='isAd'),
        ),
    ]
