# Generated by Django 4.0.6 on 2022-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_post_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ad',
        ),
        migrations.AddField(
            model_name='post',
            name='advertisement',
            field=models.BooleanField(default=False, verbose_name='Advertisement'),
        ),
    ]
