# Generated by Django 4.0.6 on 2022-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_post_ad_post_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='advertisement',
            field=models.BooleanField(default=False),
        ),
    ]
